-- insertTables.sql
-- This file inserts data using 3 methods:
-- 1. Manual INSERT commands
-- 2. Python-generated CSV files
-- 3. PostgreSQL COPY commands to load CSV files into the DB

-- Clean old data before inserting new data
TRUNCATE TABLE
    asset_incident,
    incident_assignments,
    system_backups,
    access_logs,
    incidents,
    it_assets,
    cctv_cameras,
    users,
    departments,
    roles
RESTART IDENTITY CASCADE;

-- Method 1: Manual INSERT commands
-- These rows are examples of direct insertion by INSERT.
-- The full 500 rows are then loaded by CSV with COPY.

INSERT INTO roles (role_id, role_name) VALUES
(1, 'Admin'),
(2, 'Security Manager'),
(3, 'Security Guard'),
(4, 'IT Manager'),
(5, 'IT Technician')
ON CONFLICT (role_id) DO NOTHING;

INSERT INTO departments (department_id, department_name) VALUES
(1, 'Security'),
(2, 'IT'),
(3, 'Reception'),
(4, 'Management'),
(5, 'Maintenance')
ON CONFLICT (department_id) DO NOTHING;

-- Method 2 + 3:
-- The CSV files are generated by Python script generateData.py,
-- then loaded into the database with PostgreSQL COPY.

COPY roles(role_id, role_name)
FROM '/tmp/roles.csv'
DELIMITER ',' CSV HEADER;

COPY departments(department_id, department_name)
FROM '/tmp/departments.csv'
DELIMITER ',' CSV HEADER;

COPY users(user_id, full_name, username, email, role_id, department_id, status, created_date)
FROM '/tmp/users.csv'
DELIMITER ',' CSV HEADER;

COPY cctv_cameras(camera_id, location, installation_date, last_maintenance_date, status)
FROM '/tmp/cctv_cameras.csv'
DELIMITER ',' CSV HEADER;

COPY it_assets(asset_id, asset_type, asset_name, location, purchase_date, status)
FROM '/tmp/it_assets.csv'
DELIMITER ',' CSV HEADER;

COPY incidents(incident_id, title, description, severity, reported_by, reported_date, status, camera_id)
FROM '/tmp/incidents.csv'
DELIMITER ',' CSV HEADER;

COPY system_backups(backup_id, backup_type, backup_date, status, performed_by)
FROM '/tmp/system_backups.csv'
DELIMITER ',' CSV HEADER;

COPY incident_assignments(incident_id, user_id, assigned_date, role_in_incident)
FROM '/tmp/incident_assignments.csv'
DELIMITER ',' CSV HEADER;

COPY access_logs(log_id, user_id, access_type, location, access_time, status, ip_address)
FROM '/tmp/access_logs.csv'
DELIMITER ',' CSV HEADER;

COPY asset_incident(incident_id, asset_id, relation_description)
FROM '/tmp/asset_incident.csv'
DELIMITER ',' CSV HEADER;
